name: Build Docker
on:
  push:
    paths:
      - "Dockerfile"
      - "docker-compose.yml"
  pull_request:
    paths:
      - "Dockerfile"
      - "docker-compose.yml"

jobs:
  build:
    name: Build Docker
    runs-on: ubuntu-latest
    steps:
      - name: Build HORNET Docker image
        run: docker build . --file Dockerfile --tag hornet:latest

      - name: Test HORNET Docker image
        run: docker run --rm --name hornet hornet:latest --help 2>/dev/null | grep -q "help requested"
